# This is a basic workflow to help you get started with Actions

name: pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: |
          uv python install ${{ matrix.python-version }}
          uv venv

      - name: Install project
        run: |
          uv sync --all-extras --dev

      - name: Test with pytest
        run: |
          uv run pytest -v
